#!/bin/sh

usage()
{
  echo "Usage: $0 [-h] [-n] <file list>"
  echo "  -h:  print this help screen."
  echo "  -n:  do nothing, just print the actions."
  echo "  -o h:  offset picture dates by H hours"
  exit 1;
}

while getopts "o:hn" options; do
  case $options in
    n) NOTHING=1;;
    o) OFFSET=$OPTARG;;
    h) usage;;
    \?) usage;;
    *) usage;;
  esac
done
shift $((OPTIND-1))

while [ ! -z "$1" ]; do
	file=$1; shift
	origdate=`exiftool -DateTimeOriginal -d "%Y-%m-%d %H:%M:%S" "$file" |colrm 1 34`
	if [ ! -z "$origdate" ]; then
	  if [ -z $OFFSET ]; then
	    picdate=`date -d "$origdate" +%Y_%m%d_%H%M%S`
	  else
	    picdate=`date -d "$origdate $OFFSET hours" +%Y_%m%d_%H%M%S`
	  fi
	fi	
	dirname=`dirname "$file"`
	newname="${picdate}.jpg"
	if [ ! -z $picdate ]; then
    # if file exists, make it unique
    u=0
    while [ -e "$dirname/$newname" ]; do
      u=$((u+1))
      newname="${picdate}_`printf "%003d" $u`.jpg"
    done
	  [ -z $NOTHING ] && mv -b "$file" "$dirname/$newname";
	  echo "$file -> $dirname/$newname";
	else
	  echo Warning: no EXIF date for $file. Not moved.
	fi
done
